# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables: 
  csprojpath : 'api/**/*.csproj'

steps:
- task: DotNetCoreCLI@2
  name: "dotnet restore"
  inputs:
    command: 'restore'
    projects: '$(csprojpath)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(csprojpath)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(csprojpath)'
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    modifyOutputPath: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'api'
    publishLocation: 'pipeline'