# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - 'frontend'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'frontend'

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    workingDir: 'frontend'
    customCommand: 'run build'

- task: PublishPipelineArtifact@1
  displayName: 'publish artifact'
  inputs:
    targetPath: 'frontend/build'
    artifact: 'cmf-frontend'
    publishLocation: 'pipeline'